### ISSUE TITLE
Can't require with browserify

### ISSUE THREAD

**Issue by anaumidis** [Volicon/backbone.nestedTypes#100]
When I try to require it like this:
`var Nested = require("nestedtypes");`

Browserify throws this error:
`>> Error: Cannot find module 'nestedtypes' from '/[PathToSourceDirectory]' `

When I try to require it like this:
`var Nested = require("backbone.nested-types");`

Browserify throws this error: 
`>> Error: Cannot find module './object+' from '/node_modules/backbone.nested-types' `
or
`>> Error: Cannot find module './backbone+' from '/node_modules/backbone.nested-types' `

**Comment by gaperton** [comment]
You install it with npm. correct?

**Comment by anaumidis** [comment]
Yes.

**Comment by nburwell** [comment]
I'm seeing the same thing.  Using npm / browserify:

```
npm install backbone.nested-types --save-dev
```

Then in code

```
var Nested = require('nestedtypes');
```

**Comment by gaperton** [comment]
Will fix it in a few days. Next version is almost ready to deploy.

**Comment by gaperton** [comment]
Should be fixed. Try to install with:

`npm install nestedtypes`

Reopen if problem will persist.
