### ISSUE TITLE
You mention v1.1.5 but there's no branch or tag for it in the repo

### ISSUE THREAD

**Issue by far-blue** [Volicon/backbone.nestedTypes#121]
Hello :)

Your readme mentions v1.1.5 as being the latest version but there's no tag for it or branch for it in the repo so bower can only see v1.0.0.

**Comment by gaperton** [comment]
That's fine, v1.1.5 is in 'master' branch now, and is uploaded to npm. But package name is changed, now you should use `npm install nestedtypes`. Probably that's the reason.

He're s package.json from master as a prooflink :)
https://github.com/Volicon/backbone.nestedTypes/blob/master/package.json
