### ISSUE TITLE
The Bower package is stuck at v1.0.0 because there are no tags in the repo

### ISSUE THREAD

**Issue by far-blue** [Volicon/backbone.nestedTypes#122]
Unlike NPM, Bower directly accesses the git repo and bases version numbers on tags or branches and so it is stuck at v1.0.0 because that was the last tag in the repo. Would it be possible to add a tag to match each NPM release so that the Bower packages are also available?

**Comment by gaperton** [comment]
I see. I will try.

**Comment by gaperton** [comment]
Done. Reopen if it won't help.

**Comment by far-blue** [comment]
It looks correct from what I can see via `bower info` although if you wanted to change the name of the package in bower you will need to update the name in the bower.json file and also, I think, register the new package with bower :) Currently v1.1.5 is available via the backbone.nested-types package name.

**Comment by gaperton** [comment]
Ok, try now.

Registered as 'nestedtypes', should work ok.

**Comment by far-blue** [comment]
Looks correct, although as something in my project is now broken I've pinned at an earlier version while I fix things :) I assume it's the 2 different versions of Backbone. It's a sign the bower package is now up-to-date though ;)

**Comment by gaperton** [comment]
Just put an alias to point to nestedtypes instead of backbone. You don't need another instance of backbone.

**Comment by far-blue** [comment]
Yeah, I just didn't have time to do that before. Sorted now :) Although dropping back to Backbone 1.1.2 has thrown up some issues / bugs I need to work around. The bower package is confirmed as working, though :)

**Comment by gaperton** [comment]
Talking about bugs - its there anything else important besides polymorphic collections?

**Comment by far-blue** [comment]
The one that caught me out yesterday was that Backbone 1.1.x ignores the 'parse: false' option when using save(). Because the return from a save() in our API is not a model data structure switching back to Backbone 1.1.x caused parse errors on save.

Tbh, (and this is somewhat off topic...) our API is really not suited to Backbone's concept of REST so today I gave in and have re-implemented save, fetch, destroy and collection fetch to suit our needs. Basically, our API doesn't return an updated data structure on save / create, as Backbone expects (you need to do another fetch), and we have some coupling in our collections so, sometimes, changing a model instance requires the whole collection to be reloaded. Oh, and we have very large collections so 'fetch' really doesn't cut it - we need different types of fetch and we need query filters (which we need to track so we can re-fetch later). 'fetch'ing our 'packages' data without filters would result in over a million model instances... On top of this, we don't directly use jQuery but have an API layer that handles authentication tokens, aggregation of requests, timeouts, etc. so pretty much all of Backbone's assumptions about REST are wrong for us.

I really like the approach Ampersand has had, separating out the REST stuff in separate packages but I don't see Backbone doing that any time soon. It would be nice to see the Object/Event stuff in NestedTypes available as a separate component because we are currently using a home-rolled 'copy' of Backbone's concept of a base class with extend() support which we use all over the place - including lots of places we don't use Backbone and wouldn't want to have a dependency on all of NestedTypes :)

**Comment by gaperton** [comment]
> It would be nice to see the Object/Event stuff in NestedTypes available as a separate component because we are currently using a home-rolled 'copy' of Backbone's concept of a base class with extend() support which we use all over the place - including lots of places we don't use Backbone and wouldn't want to have a dependency on all of NestedTypes :)

Well, object system is already perfectly separated. Just grab src/object+.js, it does't have any side dependencies. You'll get Object.extend() function, with native properties definitions support and all the features documented here: http://volicon.github.io/backbone.nestedTypes/#object.extend I planned to isolate Events core (and rewrite it) later, but it always happens something more important.

**Comment by gaperton** [comment]
And yes, it would be very good to separate CRUD methods. Model core doesn't depend on that stuff too much, it's mostly generic serialization engine. The thing which really stopped me from doing this before was compatibility with upcoming backbone releases. But now all that things are possible.

**Comment by gaperton** [comment]
> The one that caught me out yesterday was that Backbone 1.1.x ignores the 'parse: false' option when using save(). Because the return from a save() in our API is not a model data structure switching back to Backbone 1.1.x caused parse errors on save.

One of options to handle that, is to override 'parse' in your base model class, and convert responses which are not valid from backbone's point of view to an empty object. Then, it will become no-op. `parse` receive options as second parameter, so you can see the context of operation in options.xhr. Before return you will need to pass data through  this._parse to give NestedTypes a change to do some attribute magic.

Regarding collection - yes, looks like fetch needs to be completely overriden in the base class. That's fine, there are no other way to make queries out of box. Just make sure you assign your base Collection to your base Model (BaseModel.Collection = BaseCollection), or, which is safer, use inline collection definition inside of your model.
