### ISSUE TITLE
Polymorphic nested Models

### ISSUE THREAD

**Issue by sklobovskaya** [Volicon/backbone.nestedTypes#61]
I have a common use case in my project where I have a Model which contains a nested Model, whose type/constructor is determined at runtime. It's a "polymorphic" attribute, if you will, but it will always be another NestedTypes Model.

Because the nested Model type is not known _a priori_, I can't declare a type/constructor for it in the outer Model. But this also means I can't take advantage of much of NestedTypes' handy functionality, like deep-setting, for that nested Model.

    var ParentModel = NestedTypes.Model.extend({
      defaults: {
        nestedModel: null // a "polymorphic" attribute
      }
    });
    var model = new ParentModel();

    // Over the course of operation, app will assign various Models to `nestedModel`. e.g.:
    model.nestedModel = new AnotherModel({ color: 'red', angle: 75 });
    model.nestedModel = new YetAnotherModel({ width: 6, texture: 'wooden' });

    // Deep-setting will not work, however, and will simply set `nestedModel` to the object literal
    // Even though I did not declare a constructor for `nestedModel`, it would be great if this worked!
    model.nestedModel = {
       width: 10
    };

What would you recommend as a solution for this use case?

If there was a way to modify the attribute spec at runtime, for example, my app could specify a constructor at any point that it needs to change, which would allow me to take advantage of deep-setting (which is necessary if I need to call model.fetch(), for example). But I realize that it may be by design that you haven't exposed that.

Thanks!

**Comment by gaperton** [comment]
When you just write 'null', you turn off all type casting logic for the attribute. But you could provide the type and still make it null by default.

```javascript
var ParentModel = NestedTypes.Model.extend({
  defaults: {
    nestedModel: NestedTypes.Model.value( null )
  }
});
```

And your example should work.

**Comment by sklobovskaya** [comment]
Turning off type casting doesn't resolve my issue. I want to be able to use deep-set on the nested Model, which doesn't work precisely because type casting is turned off.

Try this:

```javascript
var NestedModel = Backbone.NestedTypes.Model.extend({
  defaults: {
    foo: 'Foo'
  }
});
var ParentModel = Backbone.NestedTypes.Model.extend({
  defaults: {
    nestedModel: null // nestedModel attribute type casting is off
  }
});
// Create a new Model
var model = new ParentModel();
// Set the nestedModel attribute to be a new instance of NestedModel
model.nestedModel = new NestedModel();
// Try to deep-set nestedModel.foo
model.set({
  nestedModel: {
    foo: 'Bar'
  }
});
// model.nestedModel is set object literal {foo: "Bar"}, and no longer an instance of NestedModel, because no type-casting for nestedModel
console.log(model.nestedModel); 
```

**Comment by sklobovskaya** [comment]
Ah, my bad. This is what I get for trying to read too quickly. `NestedTypes.Model.value( null )` is what I was looking for -- I missed it in your documentation, which is my fault. Thanks for the explanation.

**Comment by gaperton** [comment]
You could create base model for your models, and use it instead of Nested.Model. That would be better.

Also, if you will need them to be deserialized properly, let me know, I will explain the pattern.

**Comment by gaperton** [comment]
Hope you're enjoying the library :)

**Comment by sklobovskaya** [comment]
NestedTypes has been a really solid and powerful foundation for our app's data model, no complaints at all. :-)

If you don't mind, what's an example of what you mean by "base model for polymorphic model"? I'm not sure I can have the polymorphic model extend any base model, because each model's property spec is completely different, even though it has the same role in the parent model.

**Comment by gaperton** [comment]
For example, I have dashboard with widgets of different types, which should be placed in the grid cells. I need it to serialize its state.

So, I create the base class (model) for the widget. 
```
exports.Widget = Nested.Model.extend({
    defaults : {
        type : String.value( null )
    }
});
```

All widgets types will extend this type. Also, since I need to deserialize them, and I don't know which type I need to use in advance, I will need to add some factory method.

```
exports.DashboardCell = Model.extend({
    defaults : {
        x : Integer,
        y : Integer,
        widget : Widget.options({
            parse : Widget.create
        })
    },
});
```

And I need to assign Widget.create function from somewhere, in order to avoid circular module reference (I assume we're using CommonJS/AMD modules to keep widget definitions in separate modules, so you can't have circular 'require' directive).

```
Widget.create = function( json ){
    return new allWidgets[ json.type ]( json )l
}
```

In the case you don't need serialization, it's also make sense to create the base class with an empty attributes, just to give to the reader of your code an idea which types are really possible in your polymorphic attribute. Cause, code must be written for the human first.

**Comment by sklobovskaya** [comment]
Great, thanks a lot. We actually also have the concept of a dashboard with widgets in our app, and I did  something very similar to the factory pattern you demonstrated above, though I didn't make as good use of the attribute spec as you did in your example. I'll try the same approach here.

**Comment by gaperton** [comment]
By the way, I just noticed that there's a mistake.  parse : Widget.create won't work, since its undefined on the moment of the module load. So, you'll need to wrap it in a function. Otherwise, this approach works.
