### ISSUE TITLE
Well Typed Recursive object not supported

### ISSUE THREAD

**Issue by blloyd75** [Volicon/backbone.nestedTypes#62]
A basic structure like

Message: {
Replies:[{Message},..]
};

cannot be supported.  There is no way to create a typed child which has a default of NULL of the same type being created (to stop the infinite recursion) or to create a child attribute that is a collection of the type being created.

**Comment by gaperton** [comment]
Well, the good news is that it _can_ be supported, and even will look reasonably well. Function defaults' body can be used to make recursive type references. Some work is required, though.

Will make it a part of the next major release.

**Comment by gaperton** [comment]
Even easier. I will just add pre-declarations. It will resolve all problems with circular dependencies. Will look like this:

```
var M = Model.extend();
M.define({
// actual definition
});
```

'.define' can be called several times, and will have the semantic of mixin. May be, I will call it '.mixin'.

**Comment by kkilictepe** [comment]
Any update on this issue?

**Comment by gaperton** [comment]
Got a solution in 'develop' branch, seems to work ok. Need to add unit test and merge it to 'master'.

On the next week you'll have it.

**Comment by kkilictepe** [comment]
Thanks you very much.

**Comment by kkilictepe** [comment]
Hi again, 
Please let me know how I can use new feature.
