### ISSUE TITLE
Model isValid() not calling attribute-level validation

### ISSUE THREAD

**Issue by sklobovskaya** [Volicon/backbone.nestedTypes#64]
Calling isValid() on a NestedTypes Model does not call attribute-level isValid() methods.

On line 455: https://github.com/Volicon/backbone.nestedTypes/blob/master/nestedtypes.js#L455

Looks like `this.attribute` should be `this.__attributes`, since it's trying to iterate through the attribute spec?

**Comment by gaperton** [comment]
No. Just this.attribute -> this.attributes
