### ISSUE TITLE
Using lodash as replacement for underscore results in error: Uncaught TypeError: Cannot redefine property: has

### ISSUE THREAD

**Issue by zeroedin-bill** [Volicon/backbone.nestedTypes#85]
I am using lodash instead of underscore, and lodash defines a ```has``` method on chained objects. Since backbone uses underscore, backbone models automatically inherit lodash's methods.

The recent version bump to 1.0.0 added code to the attach method that defines a property 'has' on objects attached. Since lodash has already defined that prop, it throws a TypeError: Cannot redefine property: has

**Comment by gaperton** [comment]
It's very strange. I'm adding .has to constructor functions only, not to the models itself. Why it's the problem?

I guess I need to try it by myself.

**Comment by gaperton** [comment]
Unit test passes with lodash. Volicon products run well too (it's 40K SLOC). I see no problem with NestedTypes.

This...
> I am using lodash instead of underscore, and lodash defines a has method on chained objects. Since backbone uses underscore, backbone models automatically inherit lodash's methods.

...shouldn't be a problem, cause NestedTypes set 'has' property for Model constructor function, not the model itself. 

So, problem should be somewhere else. Could you show me complete information you have? Stacktrace and exact object state which is the subject of defining 'has'.

**Comment by zeroedin-bill** [comment]
I'll attempt to reproduce this morning and get more info.

**Comment by zeroedin-bill** [comment]
@gaperton I attempted to track this down, and it looks like the issue only cropped up when some dependencies were being loaded via requirejs, and others via webpack. After refactoring to move more dependencies into webpack, the issue is resolved. Very strange. We're working towards eliminating requirejs right now, and this isn't the first such bump in the road we've found.
